version: 0.0
os: windows
files:
  - source: /
    destination: C:\deployedcontent\ER-Frontend
hooks:
  BeforeInstall:
    - location: C:\Scripts\StopProcesses.ps1
  AfterInstall:
    - location: C:\Scripts\RestartProcesses.ps1
