version: 0.0
os: windows
files:
  - source: /
    destination: C:\Apache24\htdocs
hooks:
  BeforeInstall:
    - location: Scripts\StopProcesses.ps1
      timeout: 300
      runas: root
  AfterInstall:
    - location: Scripts\RestartProcesses.ps1
      timeout: 300
      runas: root
