version: 0.0
os: windows
files:
  - source: \
    destination: C:\Apache24\htdocs
hooks:
  BeforeInstall:
    - location: C:\Scripts\StopProcesses.ps1
      timeout: 300
      runas: root
  AfterInstall:
    - location: C:\Scripts\RestartProcesses.ps1
      timeout: 300
      runas: root
