version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 17.4.0
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
