version: 0.2

phases:
  pre_build:
    commands:
      - npm install react react-dom --save
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
